export const OPEN_LOGIN_MENU = 'OPEN_LOGIN_MENU';
export const CLOSE_LOGIN_MENU = 'CLOSE_LOGIN_MENU';
export const OPEN_REG_MENU = 'OPEN_REG_MENU';
export const CLOSE_REG_MENU = 'CLOSE_REG_MENU';
export const OPEN_STARTUP_MENU = 'OPEN_STARTUP_MENU';
export const CLOSE_STARTUP_MENU = 'CLOSE_STARTUP_MENU';
export const OPEN_STARTUP_POPUP = 'OPEN_STARTUP_POPUP';
export const CLOSE_STARTUP_POPUP = 'CLOSE_STARTUP_POPUP';